python run.py --workspace="n_rigid_mi.iws" ^
              --description="Rigid registration with NCC similarity" ^
              --timer=40
python run.py --workspace="n_rigid_ncc.iws" ^
              --description="Rigid registration with NCC similarity" ^
              --timer=50
python run.py --workspace="n_rigid_ssd.iws" ^
              --description="Rigid registration with SSD similarity" ^
              --timer=50
python run.py --workspace="n_affine_mi.iws" ^
              --description="Affine registration with MI similarity" ^
              --timer=50
python run.py --workspace="n_affine_ncc.iws" ^
              --description="Affine registration with NCC similarity" ^
              --timer=50
python run.py --workspace="n_affine_ssd.iws" ^
              --description="Affine registration with SSD similarity" ^
              --timer=50
python run.py --workspace="t_rigid_mi.iws" ^
              --description="Rigid registration with MI similarity" ^
              --timer=150
python run.py --workspace="t_rigid_ncc.iws" ^
              --description="Rigid registration with NCC similarity" ^
              --timer=150
python run.py --workspace="t_rigid_ssd.iws" ^
              --description="Rigid registration with SSD similarity" ^
              --timer=150
python run.py --workspace="t_affine_mi.iws" ^
              --description="Affine registration with MI similarity" ^
              --timer=150
python run.py --workspace="t_affine_ncc.iws" ^
              --description="Affine registration with NCC similarity" ^
              --timer=150
python run.py --workspace="t_affine_ssd.iws" ^
              --description="Affine registration with SSD similarity" ^
              --timer=150