name : master-thesis
channels:
  - conda-forge
dependencies:
  - numpy==1.16.2
  - tensorflow==1.13.1
  - nibabel==2.5.1
  - tqdm
  - typed-ast
  - pytorch 
  - torchvision
  - imageio
  - ipython
  - matplotlib
  - scikit-image